services:
  test_db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: 'pismo'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres-db-volume:/var/lib/postgresql/test/data

# volumes:
#   postgres-db-volume:
